
post http://localhost:8000/pet
Content-Type: application/json
Accept: application/json

  {
    "type": "Dog",
    "name": "Shadow",
    "adoption_status": "Available",
    "picture": "https://images.squarespace-cdn.com/content/5c52811f1137a633536d811e/1588448958214-MUJZVHNJ7FXYLPXHSMWO/Homeward+Bound+Shadow.jpg?format=1500w&content-type=image%2Fjpeg",
    "height": "40cm",
    "weight": "2.5 kg",
    "color": "off white",
    "bio": "Male",
    "hypoallergenic": "true",
    "age": 9,
    "breed": "golden",
    "dietary_restrictions": "no fish"
  }


//{
  # "_id": {
  #   "$oid": "63f9f2e34181f659580fe8ec"
  # },
  # "type": "Dog",
  # "name": "Shadow",
  # "adoption_Status": "Available",
  # "picutre": "",
  # "height": "40cm",
  # "weight": "2.5 kg",
  # "color": "off white",
  # "bio": "Male",
  # "age": 9,
  # "Hypoallergenic": false,
  # "dietary_restrictions": "no fish",
  # "breed": "golden",
  # "img": "https://images.squarespace-cdn.com/content/5c52811f1137a633536d811e/1588448958214-MUJZVHNJ7FXYLPXHSMWO/Homeward+Bound+Shadow.jpg?format=1500w&content-type=image%2Fjpeg",
  # "join_date": {
  #   "$timestamp": {
  #     "t": 1677325859,
  #     "i": 1
  #   }
  # },


###
get http://localhost:8000/pet/63f9f711b2ac0c536433a982
Content-Type: application/json
###
put http://localhost:8000/pet/ :id
###
get http://localhost:8000/pet
###
post http://localhost:8000/pet/ :id/adopt
###
post http://localhost:8000/pet/ :id/return
###
post http://localhost:8000/pet/:id/save
###
delete http://localhost:8000/pet/ :id/save
###
get http://localhost:8000/pet/user/ :id


